### ISSUE TITLE
[OS X] Switching branches from command line causes Atom to open/take focus

### ISSUE THREAD

**Issue by dabrady** [dbslone/git-tabs#8]
On OS X El Capitan, when the Atom application is open, switching branches from the command line (and presumably, anywhere outside of an Atom plugin) causes Atom to take over application focus, opening a new window if necessary.

This behavior is subverted when opting to use the confirmation dialog in the package settings, but ideally the context switch would happen in the background, without wrenching focus: it's annoying to be doing things in my terminal, switch branches and then suddenly find myself back in my text editor when I had no intention of being there.

**Comment by dbslone** [comment]
@dabrady I agree I've been dealing with the same frustration, I think something changed in a recent atom update because it would happen in the background before. Going to take a look again and see what I can do to prevent Atom from taking foreground focus.

**Comment by dbslone** [comment]
@dabrady I have an issue open on the Atom project now here is the issue https://github.com/atom/atom/issues/15328 if you want to track it as well.

**Comment by SKalt** [comment]
I'm still experiencing the problem, but I've been able to work around it with `atom.workspace.open`.
Minimal steps to reproduce:
```javascript
// call, blur the application, and wait for both these snippets
setTimeout(() => {
	console.log('opeing tabs via atom.open will focus the application')
	atom.open({pathsToOpen: '~/readme.md', newWindow: false})
}, 5000)
```
```javascript
setTimeout(() => {
	console.log('opeing tabs via atom.workspace.open will not focus the application')
	atom.workspace.open('README.md')
}, 5000)
```
